export const RNComponents = [
  'View',
  'Text',
  'Image',
  'ScrollView',
  'TouchableOpacity',
  'TextInput',
  'FlatList',
  'SectionList',
  'Pressable',
  'SafeAreaView',
  'StatusBar',
  'ActivityIndicator',
  'Switch',
  'Modal',
  'TouchableHighlight',
  'TouchableWithoutFeedback',
  'KeyboardAvoidingView',
  'VirtualizedList',
] as const;